### ISSUE TITLE
Portals cause projectiles to swap teams

### ISSUE THREAD

**Issue by Flinnshadow** [SamsterBirdies/pilotable-planes#1]
Would need to either create a new projectile to swap back to the correct team, do some work in ai.lua or there may be a object base approach I don't know of

**Comment by SamsterBirdies** [comment]
sounds good. reading ai.lua though😨.

**Comment by SamsterBirdies** [comment]
ig your commit fixed this?

**Comment by Flinnshadow** [comment]
> ig your commit fixed this?

Uh yeah, was waiting till you merged and double checked it to close it
