### ISSUE TITLE
Plane Anti Air

### ISSUE THREAD

**Issue by Flinnshadow** [SamsterBirdies/pilotable-planes#4]
While not necessary, an improvement on some anti air systems may lead to better gameplay as it would allow for less bullets in the air at any given time.

Anti air logic does not account for accelerating objects, it may be worthwhile to attempt to sometimes account current acceleration, especially when the target approaching directly while accelerating (therefor not being hit), or accounting for possible acceleration in any direction, adding AI weapon groups for anti air would also allow for spread fire without extra calculations.

Flak air detonation. It would likely be worthwhile to detonate an amount of the flak fired with a random offset of the target in order to reduce the amount of damage to unintended targets such as enemy bases, or friendly planes.

While working on the AI there would be a few possible performance optimizations you could do, such as recording projectile positions for later use or culling some AA weapon calls.

Sidewinders. They are quite hard to use as anti air, adding some level of tracking, perhaps with some fuel or lifetime restriction may be worthwhile. (I do have an efficient, closest projectile, tracker if there are issues on performance, else I imagine simply ignoring any other projectiles once locked on would be quite efficient.

Lasers. Mainly the plasma, are quite powerful, a damage multiplier to allow for slight singes with the beam would be appreciated.

**Comment by SamsterBirdies** [comment]
youve done a absolute poop ton of work on the AI and AA for this mod so ill close this as completed.
